name: Python Code Quality Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GH_PAT }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install autopep8 pylint pyright
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Apply autopep8 formatting
      run: |
        autopep8 --in-place --aggressive --aggressive --recursive src/
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git diff --staged --exit-code || git commit -m "Apply autopep8 formatting"
        git push

    - name: Run pylint
      run: pylint src/ || echo "Pylint reported issues"

    - name: Run pyright
      run: pyright src/ || echo "Pyright reported issues"

    # - name: Pylint GitHub Action
    #   uses: Silleellie/pylint-github-action@v2
    #   with:
    #     lint-path: src
    #     python-version: 3.9
    #     readme-path: README.md
    #     badge-text: PyLint
    #     color-bad-score: red
    #     color-ok-score: orange
    #     color-good-score: yellow
    #     color-perfect-score: brightgreen
